[snapshot]
max-new-file-size = "3MiB"

[user]
name = "Jaeyong Choi"
email = "jayong93@linecorp.com"

[ui]
merge-editor = "vimdiff"
diff-editor = ["nvim", "-c", "DiffDirs $left $right"]
editor = "nvim"
default-command = "status"
diff-instructions = false

[ui.diff]
tool = ["difft", "--color=always", "$left", "$right"]

[merge-tools]

[merge-tools.vimdiff]
program = "nvim"
merge-tool-edits-conflict-markers = true

[aliases]
gf = ["git", "fetch", "--all-remotes"]
bs = ["branch", "set"]
push = ["git", "push"]

[revset-aliases]
'HEAD' = '@-'
'MOD' = 'latest(::@ ~ empty())'

[revsets]
log = 'ancestors(branches() | remote_branches(), 3)::(@ | visible_heads())'
