version: '3'

services:
    ftp:
        container_name: ftp
        image: stilliard/pure-ftpd:hardened
        volumes:
            - ./pure-ftp/passwd:/etc/pure-ftpd/passwd
            - ./pure-ftp/private:/etc/ssl/private
            - ./pure-ftp/logs:/var/log
            - /home/ftpusers:/home/ftpusers
        restart: always
        environment:
            PUBLICHOST: localhost
            LANG: C.UTF-8
            ADDED_FLAGS: -d -d
        ports:
            - "21:21"
            - "30000-30009:30000-30009"

    qbittorrent:
        container_name: qbittorrent
        image: linuxserver/qbittorrent
        volumes:
            - ./qbittorrent/config:/config
            - ./qbittorrent/watch:/watch
            - /home/ftpusers/files:/downloads
        restart: always
        environment:
            PUID: ${QBT_UID}
            PGID: ${QBT_GID}
            TZ: Seoul
            UMASK_SET: 002
            WEBUI_PORT: 8090
        ports:
            - "8090:8090"
            - "6881:6881"
            - "6881:6881/udp"

    samba:
        container_name: samba
        image: dperson/samba
        volumes:
            - /home/ftpusers:/mount/share
        restart: always
        ports:
            - "139:139"
            - "445:445"
        environment:
            TZ: Seoul
        command: [-w, "WORKGROUP",
            -u, "gclock;032060;${QBT_UID};",
            -s, "share;/mount/share;;;no;;;;shared files",
            -g, "hosts allow = 192.168.219."]
