[scripts.mem-usage]
alias = 'mem-usage'
command = 'ps -eo rsz,cmd | grep "^\s*[0-9]\+ $0" | grep -v grep'

[scripts.git-pushall]
alias = 'git-pushall'
command = 'git remote | xargs -I{} git push --all {}'

[default]
